//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpress.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServicioDeEntregasEntities : DbContext
    {
        public ServicioDeEntregasEntities()
            : base("name=ServicioDeEntregasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbClientes> tbClientes { get; set; }
        public DbSet<tbContrato> tbContrato { get; set; }
        public DbSet<tbEntregas> tbEntregas { get; set; }
        public DbSet<tbEstados> tbEstados { get; set; }
        public DbSet<tbPagos> tbPagos { get; set; }
        public DbSet<tbRepartidor> tbRepartidor { get; set; }
        public DbSet<tbRoles> tbRoles { get; set; }
        public DbSet<tbTipoContrato> tbTipoContrato { get; set; }
        public DbSet<tbFacturas_Recibos> tbFacturas_Recibos { get; set; }
    }
}
