//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbClientes
    {
        public tbClientes()
        {
            this.tbContrato = new HashSet<tbContrato>();
            this.tbEntregas = new HashSet<tbEntregas>();
        }
    
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string RFC { get; set; }
        public Nullable<int> ROL { get; set; }
        public string Contraseña { get; set; }
    
        public virtual tbRoles tbRoles { get; set; }
        public virtual ICollection<tbContrato> tbContrato { get; set; }
        public virtual ICollection<tbEntregas> tbEntregas { get; set; }
    }
}
