//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEntregas
    {
        public int idOrden { get; set; }
        public int idCliente { get; set; }
        public Nullable<int> idRepartidor { get; set; }
        public string NombreConsumidor { get; set; }
        public string DireccionConsumidor { get; set; }
        public int Estado { get; set; }
        public string TelefonoConsumidor { get; set; }
        public string Descripcion { get; set; }
    
        public virtual tbClientes tbClientes { get; set; }
        public virtual tbEstados tbEstados { get; set; }
        public virtual tbRepartidor tbRepartidor { get; set; }
    }
}
