//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPagos
    {
        public tbPagos()
        {
            this.tbFacturas_Recibos = new HashSet<tbFacturas_Recibos>();
        }
    
        public int IdTransaccion { get; set; }
        public int idCliente { get; set; }
        public int idcontrato { get; set; }
        public Nullable<int> Monto { get; set; }
        public Nullable<System.DateTime> Vigencia { get; set; }
        public string NumTarjeta { get; set; }
        public string Tipotarjeta { get; set; }
    
        public virtual tbContrato tbContrato { get; set; }
        public virtual ICollection<tbFacturas_Recibos> tbFacturas_Recibos { get; set; }
    }
}
