//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRepartidor
    {
        public tbRepartidor()
        {
            this.tbEntregas = new HashSet<tbEntregas>();
        }
    
        public int IdRepartidor { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Contraseña { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> ROL { get; set; }
    
        public virtual ICollection<tbEntregas> tbEntregas { get; set; }
        public virtual tbRoles tbRoles { get; set; }
    }
}
