//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRoles
    {
        public tbRoles()
        {
            this.tbClientes = new HashSet<tbClientes>();
            this.tbRepartidor = new HashSet<tbRepartidor>();
        }
    
        public int idRol { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<tbClientes> tbClientes { get; set; }
        public virtual ICollection<tbRepartidor> tbRepartidor { get; set; }
    }
}
