//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoContrato
    {
        public tbTipoContrato()
        {
            this.tbContrato = new HashSet<tbContrato>();
        }
    
        public int IdTipoContrato { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> MontoMensual { get; set; }
    
        public virtual ICollection<tbContrato> tbContrato { get; set; }
    }
}
